import React, { useState, useEffect } from 'react';
import { Form, Input, Button, Checkbox, Table, Popconfirm, message, Select } from 'antd';
import DynamicTable from 'components/app-components/Custom/table'; // Assuming a dynamic table is used
import { ProductService } from 'services/ProductService';
import Barcode from "react-barcode";
import { MeasurementUnitService } from 'services/MeasurementService';
const { Option } = Select;


const ProductForm = () => {
    const [form] = Form.useForm();
    const [products, setProducts] = useState([]);
    const [editingProduct, setEditingProduct] = useState(null);
    const [creatingProduct, setCreatingProduct] = useState(false);
    const [barcodeValue, setBarcodeValue] = useState("");
    const [measuremen, setMeasuremen] = useState("");

    const fetchData = async () => {
        const products = await ProductService.getProducts(); // Adjust the service call accordingly
        const measurement = await getMeasurement();
        setMeasuremen(measurement.data)
        return { data: products.products, current: 1, pageSize: 10, total: 10 }; // Adjust based on actual API response
    };
    const generateBarCode = async () => {
        const autoGeneratedBarcode = `BAR-${Date.now()}`;
        setBarcodeValue(autoGeneratedBarcode);
        form.setFieldsValue({ barcode: autoGeneratedBarcode });

    }

    const getMeasurement = async() =>{
       return  await MeasurementUnitService.get()
    }

    useEffect(() => {
        const loadData = async () => {
            const data = await fetchData()
            await generateBarCode()
            setProducts(data.products);
        };
        loadData();
    }, []);

    const createProduct = async (product) => {
        return await ProductService.createProduct(product);
    };

    const updateProduct = async (productId, product) => {
        return await ProductService.updateProduct(productId, product);
    };

    const deleteProduct = async (productId) => {
        return await ProductService.deleteProduct(productId);
    };

    const handleSubmit = async () => {
        const values = await form.validateFields();
        if (values.min_stock > values.max_stock) {
            message.info('El stock mínimo no puede ser mayor que el stock máximo.');
            return
        } 

        if (editingProduct) {
            await updateProduct(editingProduct.id, values);
        } else {
            await createProduct(values);
        }

        await message.success(`Producto ${editingProduct ? 'actualizado' : 'creado'} con éxito`);
        setProducts(await fetchData());
        handleCancel();
    };

    const handleEdit = async (product) => {
        form.setFieldsValue(product);
        setEditingProduct(product);
        setCreatingProduct(true);
    };

    const handleDelete = async (product) => {
        await deleteProduct(product.id); // Assuming the product has an 'id' field
        setProducts(await fetchData());
        handleCancel();
        message.success('Producto eliminado con éxito');
    };

    const handleCancel = () => {
        form.resetFields();
        setEditingProduct(null);
        setCreatingProduct(false);
    };

    const handleCreate = () => {
        handleCancel();
        setCreatingProduct(true);
        generateBarCode();
    };

    const columns = [
        { title: 'Nombre', dataIndex: 'name' },
        { title: 'Barcode', dataIndex: 'barcode' },
        { title: 'Descripción', dataIndex: 'description' },
        { title: 'Stock Mínimo', dataIndex: 'min_stock' },
        { title: 'Stock Máximo', dataIndex: 'max_stock' },
        { title: 'Estado', dataIndex: 'status', render: (status) => (status ? 'Activo' : 'Inactivo') },
        {
            title: 'Acciones',
            render: (_, record) => (
                <span>
                    <Button onClick={() => handleEdit(record)} style={{ marginRight: 8 }}>
                        Editar
                    </Button>
                    <Popconfirm title="¿Estás seguro de eliminar?" onConfirm={() => handleDelete(record)}>
                        <Button type="danger">Eliminar</Button>
                    </Popconfirm>
                </span>
            ),
        },
    ];

    return (
        creatingProduct ? (
            <div>
                <h1>{editingProduct ? 'Editar Producto' : 'Crear Producto'}</h1>
                <Form
                    form={form}
                    layout="vertical"
                    name="product_form"
                    initialValues={editingProduct}
                    onFinish={handleSubmit}
                >
                    <Form.Item
                        name="barcode"
                        label="Código de Barras"
                        rules={[{ required: true, message: "El código de barras es obligatorio!" }]}
                    >
                        <Barcode />
                    </Form.Item>
                    <Form.Item name="id" style={{ display: 'none' }}>
                        <Input type="hidden" />
                    </Form.Item>
                    <Form.Item
                        name="name"
                        label="Nombre"
                        rules={[{ required: true, message: 'Por favor ingrese el nombre del producto!' }]}
                    >
                        <Input />
                    </Form.Item>
                    <Form.Item name="description" label="Descripción">
                        <Input />
                    </Form.Item>
                    <Form.Item
                        name="measurementUnitId"
                        label="Unidad de medida"
                        rules={[{ required: true, message: 'Por favor seleccione una unidad de medida!' }]}
                    >
                        <Select placeholder="Seleccione U. Me"  >
                            {measuremen.map((measu) => (
                                <Option key={measu.id} value={measu.id}>
                                    {measu.name}
                                </Option>
                            ))}
                        </Select>
                    </Form.Item>
                    <Form.Item
                        name="min_stock"
                        label="Stock Mínimo"
                        rules={[{ required: true, message: 'Por favor ingrese el stock mínimo!' }]}
                    >
                        <Input type="number" />
                    </Form.Item>
                    <Form.Item
                        name="max_stock"
                        label="Stock Máximo"
                        rules={[{ required: true, message: 'Por favor ingrese el stock máximo!' }]}
                    >
                        <Input type="number" />
                    </Form.Item>
                    <Form.Item name="status" label="Activo" valuePropName="checked">
                        <Checkbox></Checkbox>
                    </Form.Item>
                    <Form.Item>
                        <Button type="primary" htmlType="submit">
                            {editingProduct ? 'Actualizar' : 'Crear'}
                        </Button>
                        <Button onClick={handleCancel} style={{ marginLeft: 10 }}>
                            Cancelar
                        </Button>
                    </Form.Item>
                </Form>
            </div>
        ) : (
            <div>
                <Button onClick={handleCreate}>Crear producto</Button>
                <DynamicTable columns={columns} fetchData={fetchData} />
            </div>
        )
    );
};

export default ProductForm;
